/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejercicioextra1;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author Abigail Castro
 */
public class Planer extends javax.swing.JFrame {

    DefaultListModel<Tarea> incompletasListModel = new DefaultListModel<>();
    DefaultListModel<Tarea> completasListModel = new DefaultListModel<>();

    ArrayList<Tarea> tareasIncompletas = new ArrayList<>();
    ArrayList<Tarea> tareasCompletas = new ArrayList<>();

    /**
     * Creates new form Planer
     */
    public Planer() {
        initComponents();
        jListaIncompletas.setModel(incompletasListModel);
        jListaCompletas.setModel(completasListModel);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelListas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListaIncompletas = new javax.swing.JList<>();
        jLIncompletas = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListaCompletas = new javax.swing.JList<>();
        jLCompletas = new javax.swing.JLabel();
        jBAgregar = new javax.swing.JButton();
        jBEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Planer");
        setBackground(new java.awt.Color(0, 0, 0));
        setPreferredSize(new java.awt.Dimension(400, 300));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 300));

        jLabel1.setBackground(new java.awt.Color(73, 73, 73));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Organizador de tareas");

        jPanelListas.setBackground(new java.awt.Color(73, 73, 73));
        jPanelListas.setForeground(new java.awt.Color(73, 73, 73));

        jListaIncompletas.setBackground(new java.awt.Color(72, 70, 70));
        jListaIncompletas.setForeground(new java.awt.Color(204, 204, 204));
        jListaIncompletas.setSelectionBackground(new java.awt.Color(204, 204, 255));
        jListaIncompletas.setSelectionForeground(new java.awt.Color(102, 102, 102));
        jScrollPane1.setViewportView(jListaIncompletas);

        jLIncompletas.setBackground(new java.awt.Color(73, 73, 73));
        jLIncompletas.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLIncompletas.setForeground(new java.awt.Color(204, 204, 204));
        jLIncompletas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLIncompletas.setText("Incompletas");

        jListaCompletas.setBackground(new java.awt.Color(72, 70, 70));
        jListaCompletas.setForeground(new java.awt.Color(204, 204, 204));
        jListaCompletas.setDragEnabled(true);
        jListaCompletas.setSelectionBackground(new java.awt.Color(204, 204, 255));
        jListaCompletas.setSelectionForeground(new java.awt.Color(102, 102, 102));
        jScrollPane2.setViewportView(jListaCompletas);

        jLCompletas.setBackground(new java.awt.Color(73, 73, 73));
        jLCompletas.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLCompletas.setForeground(new java.awt.Color(204, 204, 204));
        jLCompletas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLCompletas.setText("Completas");

        javax.swing.GroupLayout jPanelListasLayout = new javax.swing.GroupLayout(jPanelListas);
        jPanelListas.setLayout(jPanelListasLayout);
        jPanelListasLayout.setHorizontalGroup(
            jPanelListasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListasLayout.createSequentialGroup()
                .addGroup(jPanelListasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelListasLayout.createSequentialGroup()
                        .addContainerGap(32, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanelListasLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLIncompletas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanelListasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelListasLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelListasLayout.createSequentialGroup()
                        .addComponent(jLCompletas)
                        .addGap(56, 56, 56))))
        );
        jPanelListasLayout.setVerticalGroup(
            jPanelListasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelListasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelListasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelListasLayout.createSequentialGroup()
                        .addComponent(jLCompletas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelListasLayout.createSequentialGroup()
                        .addComponent(jLIncompletas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );

        jBAgregar.setBackground(new java.awt.Color(73, 73, 73));
        jBAgregar.setForeground(new java.awt.Color(204, 204, 204));
        jBAgregar.setText("Agregar");
        jBAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarActionPerformed(evt);
            }
        });

        jBEliminar.setBackground(new java.awt.Color(73, 73, 73));
        jBEliminar.setForeground(new java.awt.Color(204, 204, 204));
        jBEliminar.setText("Eliminar");
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(jBAgregar)
                                .addGap(69, 69, 69)
                                .addComponent(jBEliminar)
                                .addGap(58, 58, 58))
                            .addComponent(jPanelListas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelListas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBEliminar)
                    .addComponent(jBAgregar))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
        // TODO add your handling code here:
        int index = jListaIncompletas.getSelectedIndex();
        if (index != -1) {
            //creo esta tarea en las completas
            Tarea tareaSeleccionada = tareasIncompletas.get(index);
            tareasCompletas.add(tareaSeleccionada);
            //la quito de las incompletas y actualizo la jListIncompletas
            tareasIncompletas.remove(index);
            incompletasListModel.remove(index);
            //agrego a la jListCompletas
            completasListModel.addElement(tareaSeleccionada);

            //Actualizo ambas
            jListaIncompletas.revalidate();
            jListaIncompletas.repaint();
            jListaCompletas.revalidate();
            jListaCompletas.repaint();
        }
    }//GEN-LAST:event_jBEliminarActionPerformed

    private void jBAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarActionPerformed
        // TODO add your handling code here:
        String nombreTarea = JOptionPane.showInputDialog("Tarea:");
        Tarea tarea = new Tarea(nombreTarea);

        tareasIncompletas.add(tarea);
        incompletasListModel.addElement(tarea);
        jListaIncompletas.revalidate();
        jListaIncompletas.repaint();
    }//GEN-LAST:event_jBAgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Planer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Planer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Planer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Planer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Planer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAgregar;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JLabel jLCompletas;
    private javax.swing.JLabel jLIncompletas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<Tarea> jListaCompletas;
    private javax.swing.JList<Tarea> jListaIncompletas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelListas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
