/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tutorial;

import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Abigail
 */
public class ComboView extends javax.swing.JFrame {
    //Creo una clase anónima que va a sobreescribir la que ya existe en DefaulTableModel
    private DefaultTableModel modelo = new DefaultTableModel(){
        public boolean isCellEditable(int fila, int columna){
            return false; 
        }
    };

    /**
     * Creates new form ComboAlumnos
     */
    public ComboView() {
        initComponents();
        cargarCombo();
        armarCabecera();
        cargarDatosArray();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPCarga = new javax.swing.JPanel();
        jLTitleLoad = new javax.swing.JLabel();
        jLMatriculaCarga = new javax.swing.JLabel();
        jTMatriculaCarga = new javax.swing.JTextField();
        jNombreCarga = new javax.swing.JLabel();
        jTNombreCarga = new javax.swing.JTextField();
        jLApellidoCarga = new javax.swing.JLabel();
        jTApellidoCarga = new javax.swing.JTextField();
        jBCargar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAlumnos = new javax.swing.JTable();
        jBEliminar = new javax.swing.JButton();
        jPBuscador = new javax.swing.JPanel();
        jLTitleSearch = new javax.swing.JLabel();
        jCBAlumnos = new javax.swing.JComboBox<>();
        jLMatricula = new javax.swing.JLabel();
        jTextoMatricula = new javax.swing.JTextField();
        jLNombre = new javax.swing.JLabel();
        jTextoNombre = new javax.swing.JTextField();
        jLApellido = new javax.swing.JLabel();
        jTextoApellido = new javax.swing.JTextField();
        jLTitleSearchTable = new javax.swing.JLabel();
        jLMatriculaT = new javax.swing.JLabel();
        jTMTabla = new javax.swing.JTextField();
        jLNombreT = new javax.swing.JLabel();
        jTNTabla = new javax.swing.JTextField();
        jLApellidoT = new javax.swing.JLabel();
        jTATabla = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Busqueda de Alumnos");
        setBackground(new java.awt.Color(51, 51, 51));
        setMinimumSize(new java.awt.Dimension(750, 450));
        setPreferredSize(new java.awt.Dimension(450, 750));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPCarga.setBackground(new java.awt.Color(51, 51, 51));
        jPCarga.setForeground(new java.awt.Color(102, 102, 102));
        jPCarga.setToolTipText("");

        jLTitleLoad.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLTitleLoad.setForeground(new java.awt.Color(204, 204, 255));
        jLTitleLoad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTitleLoad.setText("CARGA DE ALUMNOS");
        jLTitleLoad.setPreferredSize(new java.awt.Dimension(250, 15));
        jLTitleLoad.setRequestFocusEnabled(false);

        jLMatriculaCarga.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLMatriculaCarga.setForeground(new java.awt.Color(153, 153, 153));
        jLMatriculaCarga.setText("N° MATRICULA");

        jTMatriculaCarga.setForeground(new java.awt.Color(51, 51, 51));
        jTMatriculaCarga.setCaretColor(new java.awt.Color(102, 102, 102));
        jTMatriculaCarga.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        jTMatriculaCarga.setSelectedTextColor(new java.awt.Color(204, 204, 255));
        jTMatriculaCarga.setSelectionColor(new java.awt.Color(153, 153, 255));
        jTMatriculaCarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTMatriculaCargaActionPerformed(evt);
            }
        });

        jNombreCarga.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jNombreCarga.setForeground(new java.awt.Color(153, 153, 153));
        jNombreCarga.setText("NOMBRE");

        jTNombreCarga.setForeground(new java.awt.Color(51, 51, 51));
        jTNombreCarga.setCaretColor(new java.awt.Color(102, 102, 102));
        jTNombreCarga.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        jTNombreCarga.setSelectedTextColor(new java.awt.Color(204, 204, 255));
        jTNombreCarga.setSelectionColor(new java.awt.Color(153, 153, 255));
        jTNombreCarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNombreCargaActionPerformed(evt);
            }
        });

        jLApellidoCarga.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLApellidoCarga.setForeground(new java.awt.Color(153, 153, 153));
        jLApellidoCarga.setText("APELLIDO");

        jTApellidoCarga.setForeground(new java.awt.Color(51, 51, 51));
        jTApellidoCarga.setCaretColor(new java.awt.Color(102, 102, 102));
        jTApellidoCarga.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        jTApellidoCarga.setSelectedTextColor(new java.awt.Color(204, 204, 255));
        jTApellidoCarga.setSelectionColor(new java.awt.Color(153, 153, 255));
        jTApellidoCarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTApellidoCargaActionPerformed(evt);
            }
        });

        jBCargar.setText("Cargar");
        jBCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCargarActionPerformed(evt);
            }
        });

        jTAlumnos.setAutoCreateRowSorter(true);
        jTAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Matricula", "Nombre", "Apellido"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTAlumnos.setSelectionBackground(new java.awt.Color(153, 153, 255));
        jTAlumnos.setSelectionForeground(new java.awt.Color(204, 204, 255));
        jTAlumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTAlumnosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTAlumnos);

        jBEliminar.setText("Eliminar");
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPCargaLayout = new javax.swing.GroupLayout(jPCarga);
        jPCarga.setLayout(jPCargaLayout);
        jPCargaLayout.setHorizontalGroup(
            jPCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCargaLayout.createSequentialGroup()
                .addGroup(jPCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPCargaLayout.createSequentialGroup()
                        .addGroup(jPCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPCargaLayout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jLTitleLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPCargaLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLMatriculaCarga)
                                    .addGroup(jPCargaLayout.createSequentialGroup()
                                        .addGroup(jPCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jNombreCarga)
                                            .addComponent(jLApellidoCarga))
                                        .addGap(33, 33, 33)))
                                .addGap(46, 46, 46)
                                .addGroup(jPCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTMatriculaCarga, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTNombreCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTApellidoCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 50, Short.MAX_VALUE))
                    .addGroup(jPCargaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCargaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBEliminar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBCargar, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPCargaLayout.setVerticalGroup(
            jPCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCargaLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLTitleLoad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLMatriculaCarga)
                    .addComponent(jTMatriculaCarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTNombreCarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jNombreCarga))
                .addGap(18, 18, 18)
                .addGroup(jPCargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTApellidoCarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLApellidoCarga))
                .addGap(18, 18, 18)
                .addComponent(jBCargar)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBEliminar)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(jPCarga);

        jPBuscador.setBackground(new java.awt.Color(51, 51, 51));
        jPBuscador.setForeground(new java.awt.Color(102, 102, 102));
        jPBuscador.setToolTipText("");

        jLTitleSearch.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLTitleSearch.setForeground(new java.awt.Color(204, 204, 255));
        jLTitleSearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTitleSearch.setText("BUSCADOR DE ALUMNOS");
        jLTitleSearch.setPreferredSize(new java.awt.Dimension(250, 15));
        jLTitleSearch.setRequestFocusEnabled(false);

        jCBAlumnos.setForeground(new java.awt.Color(102, 102, 102));
        jCBAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBAlumnosActionPerformed(evt);
            }
        });

        jLMatricula.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLMatricula.setForeground(new java.awt.Color(153, 153, 153));
        jLMatricula.setText("N° MATRICULA");

        jTextoMatricula.setEditable(false);
        jTextoMatricula.setForeground(new java.awt.Color(51, 51, 51));
        jTextoMatricula.setCaretColor(new java.awt.Color(102, 102, 102));
        jTextoMatricula.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        jTextoMatricula.setSelectedTextColor(new java.awt.Color(204, 204, 255));
        jTextoMatricula.setSelectionColor(new java.awt.Color(153, 153, 255));
        jTextoMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextoMatriculaActionPerformed(evt);
            }
        });

        jLNombre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLNombre.setForeground(new java.awt.Color(153, 153, 153));
        jLNombre.setText("NOMBRE");

        jTextoNombre.setEditable(false);
        jTextoNombre.setForeground(new java.awt.Color(51, 51, 51));
        jTextoNombre.setCaretColor(new java.awt.Color(102, 102, 102));
        jTextoNombre.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        jTextoNombre.setSelectedTextColor(new java.awt.Color(204, 204, 255));
        jTextoNombre.setSelectionColor(new java.awt.Color(153, 153, 255));
        jTextoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextoNombreActionPerformed(evt);
            }
        });

        jLApellido.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLApellido.setForeground(new java.awt.Color(153, 153, 153));
        jLApellido.setText("APELLIDO");

        jTextoApellido.setEditable(false);
        jTextoApellido.setForeground(new java.awt.Color(51, 51, 51));
        jTextoApellido.setCaretColor(new java.awt.Color(102, 102, 102));
        jTextoApellido.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        jTextoApellido.setSelectedTextColor(new java.awt.Color(204, 204, 255));
        jTextoApellido.setSelectionColor(new java.awt.Color(153, 153, 255));
        jTextoApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextoApellidoActionPerformed(evt);
            }
        });

        jLTitleSearchTable.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLTitleSearchTable.setForeground(new java.awt.Color(204, 204, 255));
        jLTitleSearchTable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTitleSearchTable.setText("BUSCADOR DESDE TABLA");
        jLTitleSearchTable.setPreferredSize(new java.awt.Dimension(250, 15));
        jLTitleSearchTable.setRequestFocusEnabled(false);

        jLMatriculaT.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLMatriculaT.setForeground(new java.awt.Color(153, 153, 153));
        jLMatriculaT.setText("N° MATRICULA");

        jTMTabla.setEditable(false);
        jTMTabla.setForeground(new java.awt.Color(51, 51, 51));
        jTMTabla.setCaretColor(new java.awt.Color(102, 102, 102));
        jTMTabla.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        jTMTabla.setSelectedTextColor(new java.awt.Color(204, 204, 255));
        jTMTabla.setSelectionColor(new java.awt.Color(153, 153, 255));
        jTMTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTMTablaActionPerformed(evt);
            }
        });

        jLNombreT.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLNombreT.setForeground(new java.awt.Color(153, 153, 153));
        jLNombreT.setText("NOMBRE");

        jTNTabla.setEditable(false);
        jTNTabla.setForeground(new java.awt.Color(51, 51, 51));
        jTNTabla.setCaretColor(new java.awt.Color(102, 102, 102));
        jTNTabla.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        jTNTabla.setSelectedTextColor(new java.awt.Color(204, 204, 255));
        jTNTabla.setSelectionColor(new java.awt.Color(153, 153, 255));
        jTNTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNTablaActionPerformed(evt);
            }
        });

        jLApellidoT.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLApellidoT.setForeground(new java.awt.Color(153, 153, 153));
        jLApellidoT.setText("APELLIDO");

        jTATabla.setEditable(false);
        jTATabla.setForeground(new java.awt.Color(51, 51, 51));
        jTATabla.setCaretColor(new java.awt.Color(102, 102, 102));
        jTATabla.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        jTATabla.setSelectedTextColor(new java.awt.Color(204, 204, 255));
        jTATabla.setSelectionColor(new java.awt.Color(153, 153, 255));
        jTATabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTATablaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPBuscadorLayout = new javax.swing.GroupLayout(jPBuscador);
        jPBuscador.setLayout(jPBuscadorLayout);
        jPBuscadorLayout.setHorizontalGroup(
            jPBuscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBuscadorLayout.createSequentialGroup()
                .addGroup(jPBuscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPBuscadorLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPBuscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCBAlumnos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLTitleSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPBuscadorLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPBuscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPBuscadorLayout.createSequentialGroup()
                                .addGroup(jPBuscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLMatricula)
                                    .addGroup(jPBuscadorLayout.createSequentialGroup()
                                        .addGroup(jPBuscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLNombre)
                                            .addComponent(jLApellido))
                                        .addGap(33, 33, 33)))
                                .addGap(46, 46, 46)
                                .addGroup(jPBuscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextoMatricula, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPBuscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPBuscadorLayout.createSequentialGroup()
                                .addGroup(jPBuscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPBuscadorLayout.createSequentialGroup()
                                        .addGroup(jPBuscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLNombreT)
                                            .addComponent(jLApellidoT))
                                        .addGap(33, 33, 33))
                                    .addComponent(jLMatriculaT))
                                .addGap(46, 46, 46)
                                .addGroup(jPBuscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPBuscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTATabla, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTNTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTMTabla, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPBuscadorLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLTitleSearchTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPBuscadorLayout.setVerticalGroup(
            jPBuscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPBuscadorLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLTitleSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jCBAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPBuscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLMatricula)
                    .addComponent(jTextoMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPBuscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLNombre))
                .addGap(18, 18, 18)
                .addGroup(jPBuscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLApellido))
                .addGap(18, 18, 18)
                .addComponent(jLTitleSearchTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPBuscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTMTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLMatriculaT))
                .addGap(18, 18, 18)
                .addGroup(jPBuscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTNTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLNombreT))
                .addGap(18, 18, 18)
                .addGroup(jPBuscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTATabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLApellidoT))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        getContentPane().add(jPBuscador);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTMatriculaCargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTMatriculaCargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTMatriculaCargaActionPerformed

    private void jTNombreCargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNombreCargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNombreCargaActionPerformed

    private void jTApellidoCargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTApellidoCargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTApellidoCargaActionPerformed

    private void jCBAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBAlumnosActionPerformed
        // TODO add your handling code here:
        Alumno seleccion = (Alumno) jCBAlumnos.getSelectedItem();
        jTextoMatricula.setText(seleccion.getMatricula() + "");
        jTextoNombre.setText(seleccion.getNombre());
        jTextoApellido.setText(seleccion.getApellido());
    }//GEN-LAST:event_jCBAlumnosActionPerformed

    private void jTextoMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextoMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextoMatriculaActionPerformed

    private void jTextoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextoNombreActionPerformed

    private void jTextoApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextoApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextoApellidoActionPerformed
    
    private void jBCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCargarActionPerformed
        // TODO add your handling code here:
        try {
            int matricula = Integer.parseInt(jTMatriculaCarga.getText()); //Si ocurre un error va al catch, sino va al if
            if (jTNombreCarga.getText().isEmpty() || jTApellidoCarga.getText().isEmpty()) {
                //Si encuentra un campo vacío manda el mensaje de error y sale del método, sino sigue
                JOptionPane.showMessageDialog(this, "No debe haber campos vacíos.");
                return;
            }
            //Tomo el nombre y el apellido y los guardo en una variable local
            String nombre = jTNombreCarga.getText();
            String apellido = jTApellidoCarga.getText();
            //Creo el alumno y lo cargo
            Alumno a = new Alumno(matricula, nombre, apellido);
            cargarDatos(a);

            //Limpio los campos
            jTMatriculaCarga.setText("");
            jTNombreCarga.setText("");
            jTApellidoCarga.setText("");

        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "Formato inválido en el campo MATRICULA. Debe contener solo enteros.");
        }
    }//GEN-LAST:event_jBCargarActionPerformed
    
    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
        // TODO add your handling code here:
        int filaS = jTAlumnos.getSelectedRow();
        if (filaS != -1) {
            modelo.removeRow(filaS);
            
            jTMTabla.setText("");
            jTNTabla.setText("");
            jTATabla.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "No se ha seleccionado la fila a eliminar.");
        }
    }//GEN-LAST:event_jBEliminarActionPerformed

    private void jTATablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTATablaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTATablaActionPerformed

    private void jTNTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNTablaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNTablaActionPerformed

    private void jTMTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTMTablaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTMTablaActionPerformed

    private void jTAlumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTAlumnosMouseClicked
        // TODO add your handling code here:
        int filaS = jTAlumnos.getSelectedRow();
        if (filaS != -1) {
            int matricula = (Integer) jTAlumnos.getValueAt(filaS, 0);
            String nombre = (String) jTAlumnos.getValueAt(filaS, 1);
            String apellido = (String) jTAlumnos.getValueAt(filaS, 2);
            
            jTMTabla.setText(matricula + "");
            jTNTabla.setText(nombre);
            jTATabla.setText(apellido);
        }
        
    }//GEN-LAST:event_jTAlumnosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComboView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComboView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComboView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComboView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComboView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCargar;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JComboBox<Alumno> jCBAlumnos;
    private javax.swing.JLabel jLApellido;
    private javax.swing.JLabel jLApellidoCarga;
    private javax.swing.JLabel jLApellidoT;
    private javax.swing.JLabel jLMatricula;
    private javax.swing.JLabel jLMatriculaCarga;
    private javax.swing.JLabel jLMatriculaT;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLNombreT;
    private javax.swing.JLabel jLTitleLoad;
    private javax.swing.JLabel jLTitleSearch;
    private javax.swing.JLabel jLTitleSearchTable;
    private javax.swing.JLabel jNombreCarga;
    private javax.swing.JPanel jPBuscador;
    private javax.swing.JPanel jPCarga;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTATabla;
    private javax.swing.JTable jTAlumnos;
    private javax.swing.JTextField jTApellidoCarga;
    private javax.swing.JTextField jTMTabla;
    private javax.swing.JTextField jTMatriculaCarga;
    private javax.swing.JTextField jTNTabla;
    private javax.swing.JTextField jTNombreCarga;
    private javax.swing.JTextField jTextoApellido;
    private javax.swing.JTextField jTextoMatricula;
    private javax.swing.JTextField jTextoNombre;
    // End of variables declaration//GEN-END:variables

    //Tutorial Carga
    private void armarCabecera() {
        modelo.addColumn("MATRICULA");
        modelo.addColumn("NOMBRE");
        modelo.addColumn("APELLIDO");

        jTAlumnos.setModel(modelo);
    }

    private void cargarDatos(Alumno alumno) {
        //Usamos un vector para cargar
        modelo.addRow(new Object[]{alumno.getMatricula(), alumno.getNombre(), alumno.getApellido()});
    }
    
    private void cargarDatosArray() {

        ArrayList<Alumno> lista = new ArrayList<>();

        lista.add(new Alumno(1122, "Will", "Shakespeare"));
        lista.add(new Alumno(3344, "Jane", "Austen"));
        lista.add(new Alumno(5566, "Juana", "De Arco"));
        lista.add(new Alumno(9900, "Albert", "Einstein"));

        for (Alumno alumno : lista) {
            modelo.addRow(new Object[]{alumno.getMatricula(), alumno.getNombre(), alumno.getApellido()});
        }
    }

    //Tutorial Buscador
    private void cargarCombo() {
        jCBAlumnos.addItem(new Alumno(1122, "Will", "Shakespeare"));
        jCBAlumnos.addItem(new Alumno(3344, "Jane", "Austen"));
        jCBAlumnos.addItem(new Alumno(5566, "Juana", "De Arco"));
        jCBAlumnos.addItem(new Alumno(7788, "Napoleón", "Bonaparte"));
        jCBAlumnos.addItem(new Alumno(9900, "Albert", "Einstein"));
    }   
}
